config/routes.rb
Rails.application.routes.draw do
  resources :products

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :products
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
   validates :name, presence: true 
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
        @products = Product.all
        render json: @products
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            render json: @product, status: 201
        else
            render json: { errors: @product.errors }, status: 422
        end
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            render json: @product
        else
            render json: { errors: @product.errors }, status: 422
        end
    end

    def destroy
       @product = Product.find(params[:id])
       @product.destroy
       
       head :no_content, status: 204
    end

    private
    def product_params
        params.require(:product).permit(:name, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.update(params[:id], product_params)
  end

  private
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="alert alert-success" role="alert" style="display: none;"></div>

  <%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @product, remote: true do |f| %>
        <div class="modal-body">
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.text_field :price, class: "form-control input-lg", placeholder: "Precio del producto" %>
          </div>
        </div>

        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/products/_row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price, precision: 2) %></td>
  <td>
    <%= link_to "Editar", edit_product_path(product), remote: true %>
  </td>
</tr>

app/views/products/create.js.erb
<% if @product.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", product: @product %>');
  $('.alert-success').html("El producto ha sido creado con éxito").show();
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>

app/views/products/edit.js.erb
$('<%= j render "form", title: "Modificar Producto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1>Products</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 text-right">
      <%= link_to "Nuevo Producto", new_product_path, remote: true, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <%= render "row", product: product %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/new.js.erb
$('<%= j render "form", title: "Nuevo Producto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/products/update.js.erb
<% if @product.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @product.id %>').replaceWith(' <%= j render "row", product: @product %>');
  $('.alert-success').html("El producto ha sido modificado con éxito").show();
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>